# Generated by Django 3.1.6 on 2021-02-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210204_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comments',
            field=models.CharField(max_length=250),
        ),
    ]
