# Generated by Django 3.1.6 on 2021-02-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210205_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
