# Generated by Django 3.1.6 on 2021-02-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210206_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
