# Generated by Django 3.1.6 on 2021-02-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210206_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toxic',
            options={'ordering': ['id']},
        ),
    ]
