# Generated by Django 3.1.6 on 2021-02-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_addon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
